# Generated by Django 5.2.5 on 2025-12-31 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organisation_historicalhousehold_and_more'),
        ('django_agent_runtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconversation',
            name='anonymous_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_conversations', to='accounts.anonymoussession'),
        ),
    ]
