# Generated by Django 5.2.9 on 2026-02-03 11:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_agent_runtime', '0025_add_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='message_storage_mode',
            field=models.CharField(blank=True, choices=[('json', 'JSON (in AgentRun)'), ('normalized', 'Normalized (Message model)')], help_text='How to store conversation messages for this agent. Leave blank to use system default (MESSAGE_STORAGE_MODE setting). JSON: Messages stored in AgentRun.input/output fields (default). Normalized: Messages stored as separate Message records (enables message-level queries).', max_length=20),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], db_index=True, help_text='Message role (system, user, assistant, tool)', max_length=20)),
                ('content', models.JSONField(blank=True, default=str, help_text='Message content (string, dict, or list for structured content)')),
                ('tool_calls', models.JSONField(blank=True, default=list, help_text='Tool calls made by assistant (for assistant messages)')),
                ('tool_call_id', models.CharField(blank=True, help_text='Tool call ID this message responds to (for tool messages)', max_length=255)),
                ('name', models.CharField(blank=True, help_text='Name of the tool (for tool messages)', max_length=255)),
                ('seq', models.PositiveIntegerField(db_index=True, help_text='Sequence number within conversation (for ordering)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (model, usage, etc.)')),
                ('conversation', models.ForeignKey(help_text='The conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='django_agent_runtime.agentconversation')),
                ('run', models.ForeignKey(blank=True, help_text='The run that produced this message (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='django_agent_runtime.agentrun')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'agent_runtime_message',
                'ordering': ['seq'],
                'abstract': False,
            },
        ),
    ]
